AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Layers

  Sample SAM Template for Layers

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  TempConversionDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: LambdaTestDependencies
      Description: Dependencies for sam app [temp-units-conv]
      ContentUri: src/
      CompatibleRuntimes:
        - nodejs6.10
        - nodejs8.10
        - nodejs12.x
        - nodejs14.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain
